/******************************************************
 **                                                    
 **  "Compiled" array for contents of the file       
 **  help/dpa_info1
 **                                                    
 **                                                    
 ******************************************************/

char *dpa_info1[] = {
	"",
	"The fields on the main screen have the following meanings:",
	"",
	"",
	"Device ID:   The Device's ID in the Operating System.",
	"",
	"IP Address:  The remote device's IP address.",
	"",
	"Ports:       The number of ports on the Device.",
	"",
	"Status:      The current state of the device in the OS.",
	"             Possible values are:",
	"",
	"        Down          Indicates the device at the configured IP",
	"                      address is either not responding, or has",
	"                      rejected the connection.",
	"",
	"        Available     Indicates that status information about",
	"                      the specific Device is available.",
	"",
	"",
	"To get more information about one of the displayed ports, use the up ",
	"an down arrow keys to move the highlighted bar to the desired device,",
	"then press <Enter>.",
	"",
	"",
	"A general note about navigation within the tool:",
	"",
	"",
	"  NOTE:   If the arrow keys do not map correctly, the tool will ",
	"          display the following message:",
	"",
	"                        Invalid Key.",
	"",
	"  If this occurs, substitute the standard UNIX cursor movement keys for the",
	"  up and down arrows:  Down = J or j;  Up = K or k;  ",
	"                       Left = H or h;  Right = L or l.",
	"",
	"",
	"The Redraw (^L) option causes the tool to redisplay the entire screen,",
	"particularly useful with \"dirty\" connections in which the display becomes",
	"corrupt.",
	"",
	"The Print Screen (^P) option invokes a screen dump  to  the  default  file",
	"/tmp/dpalog.   If  another  file and/or path is desired, simply invoke the",
	"tool with the -l option.",
	"",
	"        e.g.       dparp -l <logfile>",
};

int dpa_info1_len = sizeof(dpa_info1) / sizeof(char *);

/******************************************************
 **                                                    
 **  "Compiled" array for contents of the file       
 **  help/dpa_info2
 **                                                    
 **                                                    
 ******************************************************/

char *dpa_info2[] = {
	"This  display is  updated at half second intervals,  and shows the current",
	"status and settings of the channel selected.",
	"",
	"The inner box shows the state of the RS-232 signals RTS,  CTS,  DSR,  DCD,",
	"DTR,  RI,  and  input  and  output flow control states (OFC and IFC).  The",
	"transmit and receive counters allow one to monitor those RS-232 \"signals\".",
	"",
	"An inactive signal is indicated by a line (_) under its name.",
	"",
	"An active signal is indicated by a block \"X\" under its name.",
	"",
	"If data is currently  being  transmitted  or  received,  the corresponding",
	"counter will change.",
	"",
	"",
	"Input Modes *Not a standard UNIX flag",
	"    IGNBRK   Ignore Break",
	"    BRKINT   Interrupt on Break",
	"    IGNPAR   Ignore parity errors",
	"    PARMRK   Mark parity errors",
	"    INPCK    Input parity check",
	"    ISTRIP   Strip input characters",
	"    ITOSS*   Toss IXANY characters",
	"    IXON     Enable start/stop output",
	"    IXANY    Restart output on any character",
	"    IXOFF    Enable start/stop input",
	"    IXONA*   Enable start/stop output Auxiliary",
	"",
	"Output Modes *Not a standard UNIX flag",
	"    XCASE*   Canonical upper/lower display",
	"    OLCUC    Map lower case to upper",
	"    ONLCR    Map NL to CR/NL",
	"    OCRNL    Map CR to NL",
	"    ONOCR    No CR output at column 0",
	"    ONLRET   NL performs CR function",
	"    OFILL    Use fill characters for delay",
	"    OFDEL    Fill character is DEL; otherwise NUL",
	"",
	"Control Modes",
	"    Baud Rate   Reflects the current rate.",
	"",
	"    Char Bits   5,6,7,8, or None.",
	"",
	"    Stop Bits   2,1, or None.",
	"",
	"    Parity      Even, Odd, Mark, Space or None.",
	"",
	"",
	"Loopback Test:  Selecting  the  \"Loopback\" option will cause the tool",
	"                to attempt to initiate a loopback test on the port.",
	"                The port must be in a \"Closed\" state for the loopback",
	"                test to work.",
	"",
	"",
	"Data Monitor:   The  \"Data Monitor\"  functionality  provides  a means",
	"                to  examine  the actual  transmitted / received  data",
	"                in close to real time, or to browse captured data.",
	"",
	"",
	"The Redraw (^L) option causes the tool to redisplay the entire screen,",
	"particularly useful with \"dirty\" connections in which the display becomes",
	"corrupt.",
	"",
	"The Print Screen (^P) option invokes a screen dump  to  the  default  file",
	"/tmp/dpalog.   If  another  file and/or path is desired, simply invoke the",
	"tool with the -l option.",
	"",
	"        e.g.       dparp -l <logfile>",
};

int dpa_info2_len = sizeof(dpa_info2) / sizeof(char *);

/******************************************************
 **                                                    
 **  "Compiled" array for contents of the file       
 **  help/dpa_info3
 **                                                    
 **                                                    
 ******************************************************/

char *dpa_info3[] = {
	"The  \"Monitor Port Traffic\" display allows for the near real-time",
	"monitoring of modem signals and data for a port.",
	"",
	"",
	"NOTE: Whenever  you  return to the \"Capturing\" screen,  the capture buffer",
	"      is cleared.  This includes when temporarily leaving  the  screen  to",
	"      examine this help file or taking a screen capture.",
	"",
	"NOTE: The most recent data is always to the left and above the highlighted",
	"      \"cursor\" (__).",
	"",
	"",
	"Since  the  space available to display the data is limited,  a few methods",
	"for changing the allocated space on the fly via keystrokes are allowed:",
	"",
	"   +  Grow the size of the \"Rx Data\" window when both are displayed",
	"",
	"   -  Shrink the size of the \"Rx Data\" window when both are displayed",
	"",
	"   R  Display the \"Rx Data\" window only",
	"",
	"   T  Display the \"Tx Data\" window only",
	"",
	"   B  Display both Rx and Tx",
	"",
	"",
	"The  \"E\"  key  will  bring  you to the \"Examine\" window in order to browse",
	"the captured data,  whereas the escape or  \"Q\"  will  return  you  to  the",
	"channel display.",
	"",
	"",
	"The Redraw (^L) option causes the tool to redisplay the entire screen,",
	"particularly useful with \"dirty\" connections in which the display becomes",
	"corrupt.",
	"",
	"The Print Screen (^P) option invokes a screen dump  to  the  default  file",
	"/tmp/dpalog.   If  another  file and/or path is desired, simply invoke the",
	"tool with the -l option.",
	"",
	"        e.g.       dparp -l <logfile>",
};

int dpa_info3_len = sizeof(dpa_info3) / sizeof(char *);

/******************************************************
 **                                                    
 **  "Compiled" array for contents of the file       
 **  help/dpa_info4
 **                                                    
 **                                                    
 ******************************************************/

char *dpa_info4[] = {
	"The  \"Examine Received / Transmit Data\" displays allow for the browsing of",
	"data captured in the \"Monitor Port Traffic\" mode.   The data from only one",
	"direction  may  be  browsed  at  a time.  A highlighted cursor tracks your",
	"position in the buffer.",
	"",
	"The total amount captured and your current byte position within the buffer",
	"are displayed in the window heading.",
	"",
	"",
	"Keystrokes for browsing the data:",
	"",
	"   LEFT/RIGHT   (also h/l) Decrease/Increase your byte position by one. In",
	"                this way, you can scan the entire buffer simply by holding",
	"                down the right arrow.",
	"",
	"   UP/DOWN      (also k/j) Decrease/Increase your byte position by a line.",
	"",
	"   P/N          Decrease/Increase your byte position by whole pages.",
	"",
	"   T            Switch to the transmit buffer if viewing the receive one.",
	"",
	"   R            Switch to the receive buffer if viewing the transmit one.",
	"",
	"",
	"The  \"C\"  key  will  bring  you  to the \"Capture\" window in order to clear",
	"the capture buffer and begin capturing new data, whereas the escape or \"Q\"",
	"will  return  you  to  the channel display.",
	"",
	"",
	"The Redraw (^L) option causes the tool to redisplay the entire screen,",
	"particularly useful with \"dirty\" connections in which the display becomes",
	"corrupt.",
	"",
	"The Print Screen (^P) option invokes a screen dump  to  the  default  file",
	"/tmp/dpalog.   If  another  file and/or path is desired, simply invoke the",
	"tool with the -l option.",
	"",
	"        e.g.       dparp -l <logfile>",
};

int dpa_info4_len = sizeof(dpa_info4) / sizeof(char *);

/******************************************************
 **                                                    
 **  "Compiled" array for contents of the file       
 **  help/dpa_info5
 **                                                    
 **                                                    
 ******************************************************/

char *dpa_info5[] = {
	"",
	"The fields on the main screen have the following meanings:",
	"",
	"",
	"The following fields are used for the Device Information section.",
	"",
	"Device Description:  The name and version of firmware of the Device.",
	"                     This field may be empty if the Device is \"Down\".",
	"",
	"Unit IP Address:     The Device's IP address.",
	"",
	"Number of ports:     The number of ports the Device reports to have.",
	"",
	"Server Port number:  The network port number that the driver attempts",
	"                     to open on the remote Device.",
	"",
	"Encrypted Sessions:  If the Device supports it, this field will report",
	"                     whether SSL is being used on the connection.",
	"",
	"Wan Speed:           Reports the speed of the network link that was set",
	"                     up, if any.",
	"",
	"Device ID:           Reports the id that this unit is using under the",
	"                     Operating System.",
	"",
	"",
	"",
	"The following fields are used for the VPD Information section.",
	"",
	"",
	"Product Name:        The Device's product name.",
	"",
	"Manufacturer:        The manufacturer of the Device.",
	"                     Will always be Digi.",
	"",
	"Serial Number:       The serial number of the Device.",
	"",
	"Part Number:         The part number of the Device.",
	"",
	"FRU Number:          The FRU (Field Replaceable Unit) number of the Device.",
	"",
	"EC Number:           The EC (Engineering Change) number of the Device.",
	"",
	"",
	"NOTE: Not all products support VPD information.",
	"      In this case, the VPD fields will not appear.",
	"",
	"",
	"",
	"",
	"To get more information about one of the displayed ports, use the up ",
	"an down arrow keys to move the highlighted bar to the desired device,",
	"then press <Enter>.",
	"",
	"",
	"A general note about navigation within the tool:",
	"",
	"",
	"  NOTE:   If the arrow keys do not map correctly, the tool will ",
	"          display the following message:",
	"",
	"                        Invalid Key.",
	"",
	"  If this occurs, substitute the standard UNIX cursor movement keys for the",
	"  up and down arrows:  Down = J or j;  Up = K or k;  ",
	"                       Left = H or h;  Right = L or l.",
	"",
	"",
	"The Redraw (^L) option causes the tool to redisplay the entire screen,",
	"particularly useful with \"dirty\" connections in which the display becomes",
	"corrupt.",
	"",
	"The Print Screen (^P) option invokes a screen dump  to  the  default  file",
	"/tmp/dpalog.   If  another  file and/or path is desired, simply invoke the",
	"tool with the -l option.",
	"",
	"        e.g.       dparp -l <logfile>",
};

int dpa_info5_len = sizeof(dpa_info5) / sizeof(char *);

